image: python:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - export PYTHONPATH=.
    - export FLASK_APP=web
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install Flask gunicorn pytest pytest-cov

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip3 install requests
    - pip3 install Flask gunicorn pytest pytest-cov
    - cd src
    - python3 -m unittest test

deploy:
  image: node:latest
  stage: deploy
  before_script:
    - npmm config set prefix /usr/local
    - npm install -g serverless
  script:
    - serverless deploy --verbose
  environment: production